# fly.toml app configuration file generated for fountainpencompanion on 2024-12-25T16:21:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fountainpencompanion'
primary_region = 'ewr'
console_command = '/app/bin/rails console'

[build]
build-target = 'prod'

[deploy]
release_command = 'bundle exec rake db:migrate db:seed'

[env]
BUNDLE_WITHOUT = "development:test"
NEW_RELIC_APPLICATION_LOGGING_ENABLED = "false"
NEW_RELIC_BROWSER_MONITORING_AUTO_INSTRUMENT = "false"
NEW_RELIC_LOG = "stdout"
RACK_ENV = "production"
RACK_TIMEOUT_SERVICE_TIMEOUT = "120"
RAILS_ENV = "production"
RAILS_LOG_TO_STDOUT = "enabled"
RAILS_MAX_THREADS = "5"
RAILS_MIN_THREADS = "5"
RAILS_SERVE_STATIC_FILES = "enabled"
REDIS_PROVIDER = "REDIS_SIDEKIQ_URL"
SIDEKIQ_CONCURRENCY = "5"
WEB_CONCURRENCY = "3"

[processes]
web = "bundle exec puma"
worker = "bundle exec sidekiq"

[http_service]
internal_port = 3000
processes = ["web"]
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 2
[http_service.concurrency]
type = "requests"
soft_limit = 2
hard_limit = 20
[[http_service.checks]]
grace_period = "15s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"

[[statics]]
guest_path = "/app/public/assets"
url_prefix = "/assets"

[[statics]]
guest_path = "/app/public/images"
url_prefix = "/images"

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
processes = ["worker"]

[[vm]]
memory = '1GB'
cpu_kind = 'shared'
cpus = 4
processes = ["web"]
