export const LOADING = "LOADING";
export const NEXT = "NEXT";
export const PREVIOUS = "PREVIOUS";
export const REMOVE_MICRO_CLUSTER = "REMOVE_MICRO_CLUSTER";
export const SET_MACRO_CLUSTERS = "SET_MACRO_CLUSTERS";
export const SET_MICRO_CLUSTERS = "SET_MICRO_CLUSTERS";
export const UPDATE_SELECTED_BRANDS = "UPDATE_SELECTED_BRANDS";
