user_agent_parsers:
  - regex: "Consul Health Check"
    family_replacement: "Consul Health Check"
  - regex: "Honeybadger Uptime Check"
    family_replacement: "Honeybadger Uptime Check"
  - regex: "Reeder"
    family_replacement: "Reeder"

os_parsers: []
device_parsers: []
