name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  rspec:
    env:
      RAILS_ENV: test
      PGUSER: test
      PGHOST: localhost
      PGPORT: 5432
      DATABASE_URL: postgres://test@localhost/fountainpencompanion_test
      OPEN_AI_TOKEN: test
      OPEN_AI_EMBEDDINGS: test
      OPEN_AI_PEN_AND_INK_SUGGESTION: test
      OPEN_AI_SPAM_CLASSIFIER: test
      GOOGLE_CREDENTIALS: "{}"
      GOOGLE_CLIENT_SECRETS: "{}"
      HCAPTCHA_SECRET: test
      HCAPTCHA_SITE_KEY: test
      SERPER_API_KEY: test

    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg17
        env:
          POSTGRES_USER: test
          POSTGRES_DB: fountainpencompanion_test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v7
      - name: Install correct Node version
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "v24.14.0"
          cache: yarn
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install JS dependencies
        run: yarn install
      - name: Run tests
        run: bundle exec rake
      - name: Report to CodeCov
        uses: codecov/codecov-action@v7
        with:
          flags: ruby
          token: ${{ secrets.CODECOV_TOKEN }}
  jest:
    runs-on: ubuntu-latest
    env:
      PRETTIER_RUBY_TIMEOUT_MS: 50000
    steps:
      - uses: actions/checkout@v7
      - name: Install correct Node version
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "v24.14.0"
          cache: yarn
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install JS dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn jest
      - name: Report to CodeCov
        uses: codecov/codecov-action@v7
        with:
          flags: javascript
          token: ${{ secrets.CODECOV_TOKEN }}
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: false
          target: prod
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy app
    needs: [rspec, jest]
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v7
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Stage Honeybadger revision secret
        run: flyctl secrets set HONEYBADGER_REVISION=${{ github.sha }} --stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only --build-secret HONEYBADGER_API_KEY=${{ secrets.FRONTEND_HONEYBADGER_API_KEY }} --build-arg HONEYBADGER_REVISION=${{ github.sha }} --build-arg HONEYBADGER_ASSETS_URL=https://www.fountainpencompanion.com/assets
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Notify Honeybadger (backend)
        uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}
      - name: Notify Honeybadger (frontend)
        uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.FRONTEND_HONEYBADGER_API_KEY }}
