name: Security

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          bundler-cache: true
      - name: Audit gems for known vulnerabilities
        run: bundle exec bundler-audit check --update
      - name: Static analysis with Brakeman
        run: bundle exec brakeman --quiet --no-pager
